// Package webui embeds the generated SvelteKit static build.
package webui

import (
	"embed"
	"io/fs"
)

// dist is generated by `make web`; it is not edited by hand. Only the
// .gitkeep placeholder is tracked so the package always compiles.
//
//go:embed all:dist
var dist embed.FS

// FS returns the built UI rooted at the dist directory.
func FS() fs.FS {
	sub, err := fs.Sub(dist, "dist")
	if err != nil {
		panic(err) // dist is a compile-time constant path
	}
	return sub
}
