export type AuditEvent = {
	id: number;
	at_ms: number;
	actor: string | null;
	bot_id: string | null;
	bot_name: string | null;
	action: string;
	target: string | null;
	outcome: 'ok' | 'denied' | 'failed';
};
export type AuditPage = { events: AuditEvent[]; next_before?: number };

/** Plain past-tense wording for recorded actions. */
export const actionText: Record<string, string> = {
	'bot.create': 'created the bot',
	'bot.update': 'changed its settings',
	'bot.delete': 'deleted the bot',
	'bot.start': 'started it',
	'bot.stop': 'stopped it',
	'bot.restart': 'restarted it',
	'bot.kill': 'killed it',
	'bot.ports': 'changed published ports',
	'bot.transfer': 'transferred ownership',
	'env.set': 'set variables',
	'env.reveal': 'revealed a variable',
	'env.delete': 'removed a variable',
	'files.write': 'saved a file',
	'files.delete': 'deleted a file or folder',
	'files.mkdir': 'created a folder',
	'files.move': 'moved or renamed a file',
	'files.extract': 'extracted an archive',
	'packages.edit': 'changed packages',
	'deploy.link': 'linked a repository',
	'deploy.unlink': 'unlinked the repository',
	'deploy.start': 'started a deployment',
	'backup.create': 'created a backup',
	'backup.restore': 'restored a backup',
	'backup.delete': 'deleted a backup',
	'backup.label': 'relabeled a backup',
	'access.grant': 'shared the bot',
	'access.revoke': 'removed someone’s access',
	'telemetry.key': 'created a telemetry key',
	'telemetry.revoke': 'revoked the telemetry key',
	'schedule.create': 'added a schedule',
	'schedule.update': 'changed a schedule',
	'schedule.delete': 'removed a schedule',
	'account.sign_in': 'signed in',
	'account.logout': 'signed out',
	'account.password': 'changed their password',
	'account.password_reset': 'reset their password from an emailed link',
	'account.email_alerts': 'changed alert emails',
	'account.email_news': 'changed news emails',
	'admin.announcement': 'sent an announcement',
	'account.session_revoke': 'signed out a session',
	'account.sessions_revoke': 'signed out other sessions',
	'account.key_create': 'created an SFTP key',
	'account.key_delete': 'deleted an SFTP key',
	'account.token_create': 'created an API token',
	'account.token_delete': 'deleted an API token',
	'account.disconnect': 'disconnected an account',
	'account.mfa_enable': 'turned on two-step sign-in',
	'account.mfa_disable': 'turned off two-step sign-in',
	'admin.user_create': 'added a user',
	'admin.user_update': 'changed a user',
	'admin.site_update': 'suspended or restored a site',
	'admin.sites_domain_add': 'added a sites domain',
	'admin.sites_domain_verify': 'checked a sites domain',
	'admin.sites_domain_move': 'moved sites to another sites domain',
	'admin.sites_domain_update': 'changed a sites domain',
	'admin.sites_domain_remove': 'removed a sites domain',
	'admin.environment': 'changed panel environment settings',
	'admin.restart': 'restarted the panel',
	'bot.move': 'moved the bot to another workspace',
	'deploy.publish': 'published it to a new GitHub repository',
	'deploy.push': 'pushed its files to GitHub',
	'workspace.create': 'created a workspace',
	'workspace.rename': 'renamed a workspace',
	'workspace.delete': 'deleted a workspace',
	'workspace.member_add': 'added a workspace member',
	'workspace.member_role': 'changed a member’s role',
	'workspace.member_remove': 'removed a workspace member',
	'site.create': 'created a site',
	'site.update': 'changed a site’s settings',
	'site.delete': 'deleted a site',
	'site.upload': 'published a site upload',
	'site.deploy': 'deployed a site from GitHub',
	'site.rollback': 'rolled a site back',
	'site.domain_add': 'added a custom domain',
	'site.domain_verify': 'checked a custom domain',
	'site.domain_remove': 'removed a custom domain',
	'ai.conversation_create': 'opened an AI incident',
	'ai.conversation_delete': 'deleted an AI incident',
	'ai.run_start': 'asked the AI operator',
	'ai.run_cancel': 'cancelled an AI run',
	'ai.approval': 'decided an AI approval',
	'ai.secure_input': 'entered secure values for the AI operator',
	'ai.change_revert': 'undid an AI change',
	'ai.file_apply': 'had the AI operator change a file',
	'ai.diagnostic': 'had the AI operator run a diagnostic',
	'ai.restart': 'had the AI operator restart it',
	'ai.env_input': 'set variables through the AI operator'
};
