<script lang="ts">
	let query = $state('');
	const sections = [
		{ id:'version', title:'Version and implementation status', summary:'What this build contains and what comes next.', body:['This documentation describes BotForge 0.2.0 and the changes recorded under Unreleased in the changelog. The root VERSION file is the authoritative project version and the changelog records every notable release and in-progress change.','Version 0.2.0 added the in-house documentation, expanded widget dashboards and lifecycle, Discord bot avatars, protected Prometheus metrics, and TCP/HTTP health probes. The unreleased work adds team workspaces with administrator oversight, static site hosting with custom domains, publishing bots to GitHub, and appearance options including corner styles.','The remaining staged work is tracked in docs/implementation-status.md in the source distribution. Highest priority is removing Docker socket ownership from the panel through a narrow privileged botrunner service, followed by real egress, disk, IO, and bandwidth enforcement.'] },
		{ id:'quickstart', title:'Quick start', summary:'Create, configure and run your first bot.', body:['Choose Templates for a tested starter, or create a blank bot and upload your project in Files.','Add secrets such as DISCORD_TOKEN in Environment. Secrets are encrypted at rest and never returned after saving.','Review runtime, memory and restart policy, then start the bot. Follow build output and live logs from its page.'] },
		{ id:'deploy', title:'Deployment and GitHub', summary:'Manual uploads, repositories, automatic deploys and pushing back.', body:['Manual projects can be edited in the browser or over SFTP. GitHub projects download a repository archive without installing git on the host.','Connect GitHub under Settings, link a repository in Deploy, select the branch and optional root directory, then deploy. Automatic deploys use a signed webhook.','A failed build keeps the previous generation available. Use operation history for the exact stage and output.'] },
		{ id:'publish', title:'Publishing a bot to GitHub', summary:'Create a repository from a bot and push later changes.', body:['Deploy → Publish to GitHub creates a repository under your account or organization (private by default), pushes the bot’s files as the first commit and links the bot to it, optionally with auto-deploy. For a linked bot, Push to GitHub commits the current files to the linked branch.','Pushing uses your own GitHub connection with repository access and never force-pushes: if the branch moved on GitHub, the push stops and you deploy those changes first. With a linked folder, only that folder is replaced.','.gitignore files (root and nested) are honored. Dependencies, .git, panel metadata and .env files are always left out (.env.example is kept) and panel environment variables are never pushed. The dialog lists every file before anything is created. Limits: 5,000 files, 200 MiB, 25 MiB per file.'] },
		{ id:'workspaces', title:'Workspaces and roles', summary:'Group bots and sites for a team.', body:['Every account has a Personal workspace; create team workspaces under Settings → Workspaces and add people by the email they sign in with. The sidebar switcher scopes the overview, Sites and new bots to one workspace.','Owner and Admin act as the owner of every bot and site in the workspace. Developer creates, deploys and operates bots and sites, edits files and environment variables, but cannot change resources, delete or share. Viewer only reads status and console output.','Per-bot sharing still adds access on top. Transferring a bot moves it into the new owner’s personal workspace. Administrators see every workspace, account, bot and recent deployment under Administration.'] },
		{ id:'sites', title:'Static sites and domains', summary:'Host dashboards, docs and landing pages.', body:['When the administrator enables site hosting, Sites publishes static files at <name>.<sites domain>. Upload a ZIP of your built site (a single top folder such as dist/ is unwrapped) or deploy a GitHub branch that contains built files. Every publish is a new release; earlier ones can be served again instantly.','Sites are served by a separate listener on separate host names, never on the panel’s origin. Dotfiles such as .env are never served. Options: single-page application fallback, clean URLs, and a top-level 404.html.','Add a custom domain, create the TXT record _botforge-verify.<domain> it shows plus a CNAME (or A record) to this server, then check DNS. The domain is served only after verification; with Caddy’s on-demand TLS, certificates are requested only for verified names.'] },
		{ id:'appearance', title:'Appearance', summary:'Theme, accent color and corners.', body:['Settings → Appearance chooses light, dark or system theme, one of twelve accent colors, and a corner style: Square (no rounding anywhere), Subtle, Default or Rounded. These preferences apply to the current browser.'] },
		{ id:'widgets', title:'Dashboard widgets', summary:'Publish safe, grouped dashboards from any supported SDK.', body:['Send widgets in POST /api/v1/bot-telemetry or its WebSocket. Up to 48 widgets may be changed in one push and up to 240 active widgets are returned. Keys are upserted.','Kinds: metric, status, progress, text, chart, table, link, line, area, donut, gauge, heatmap, sparkline, kv, markdown, image, log and code. Bot content stays declarative: raw HTML, CSS and JavaScript are never executed.','Optional fields: group (tab name, 48 chars), span (1, 2 or 3 columns), min_height (0–800 px), position (0–1000), and ttl_seconds (30–604800). A widget older than five minutes is marked stale.','Remove widgets with {"unpublish":["widget-key"]} in telemetry, or DELETE /api/v1/bots/{bot_id}/widgets/{widget_key} as a full bot administrator.'] },
		{ id:'widget-data', title:'Widget data shapes', summary:'Payload conventions for every renderer.', body:['metric: {value, unit?, detail?, delta?}; status: {state: good|warn|bad|neutral, text}; progress/gauge: {value, max?, label?, unit?}.','chart/line/area/sparkline: {points:[{label,value}], unit?}; donut: {values:[{label,value}]}; heatmap: {cells:[{label,value}]}.','table: {columns:[string|{label}], rows:[[string|number|{label,url}]]}; kv: {items:[{key,value}]}; text/markdown/log: {text}; code: {code, language?}; image/link: {url, alt?/label?}.'] },
		{ id:'telemetry', title:'Telemetry limits', summary:'Rates, validation and retention.', body:['The request body is at most 64 KiB. Each bot may push 60 times per minute. A named stat is stored at most once every 10 seconds.','Per push: 16 stats, 20 commands, 10 events, 48 widget updates and 48 unpublish keys. Widget data is valid non-null JSON up to 4096 bytes. Validation errors identify the offending field.','Retention is configured by the administrator from one hour to 365 days; the default is seven days. A bot also has a bounded telemetry row history.'] },
		{ id:'health', title:'Health and alerts', summary:'Heartbeats, active probes, restart behavior and notifications.', body:['Every accepted telemetry push is a heartbeat. The optional ready boolean reports whether the bot considers its Discord connection ready.','TCP and HTTP probes check a published TCP port through host loopback. Configure their interval, timeout, thresholds and startup grace under Health & alerts. An unhealthy transition can replace a stuck container once without creating a rapid restart loop.','Restart policy can stop permanently or retry process failures with bounded exponential backoff. Health rules distinguish process state, SDK heartbeat and active probe state.','Use the diagnostics page for database, container runtime, storage and runner checks.'] },
		{ id:'security', title:'Security and isolation', summary:'Current boundaries and production guidance.', body:['Bots run with resource limits, dropped capabilities and a read-only runtime where supported. Do not mount the Docker socket into bot containers. The panel host itself must be treated as privileged while it owns that socket.','Disable networking for bots that do not need it. Bandwidth intent is recorded but requires host traffic shaping for kernel enforcement. Put the panel behind TLS and keep encryption keys outside backups.','Use a dedicated host for untrusted tenants. Stronger isolation, egress allowlists, disk quotas, malware scanning and signed runtime verification are tracked platform hardening work.'] },
		{ id:'backups', title:'Backups and restore', summary:'Workspace, environment and restore safety.', body:['Manual and scheduled backups are checksummed. Environment inclusion is explicit because it contains encrypted secrets.','A restore creates a safety backup first and records verification details. Keep off-host copies; a backup on the same disk is not disaster recovery.'] },
		{ id:'automation', title:'Automation API', summary:'Tokens, idempotency and config-as-code foundations.', body:['Create scoped automation tokens under SFTP and API keys. Send an Idempotency-Key on mutating requests so CI retries do not duplicate work.','The machine-readable specification is available at /api/v1/automation/openapi.yaml. Tokens are shown once and should be kept in a secret store.'] },
		{ id:'operations', title:'Operations guide', summary:'Install, update, diagnose and recover.', body:['Deploy with the provided container or systemd units, configure the public URL, and verify /api/v1/healthz and /api/v1/readyz.','Before upgrades, take and verify a backup. Review release notes, apply the new binary or image, and confirm the schema migration and readiness checks.','For recovery, preserve the database, workspace directory and encryption keys together. Without matching key material, sealed secrets cannot be recovered.'] }
	];
	const filtered = $derived(sections.filter((s)=>(s.title+' '+s.summary+' '+s.body.join(' ')).toLowerCase().includes(query.trim().toLowerCase())));
</script>

<svelte:head><title>Documentation · BotForge</title><meta name="description" content="BotForge installation, deployment, dashboard widget, telemetry, security and operations documentation." /></svelte:head>

<div class="mx-auto max-w-7xl px-5 py-8 lg:px-8">
	<header class="border-b border-rule pb-7">
		<a href="/" class="eyebrow">BotForge</a>
		<h1 class="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Documentation</h1>
		<p class="mt-2 max-w-2xl text-title text-muted">Run bots, ship safely, and build dashboards without leaving the panel.</p>
		<label class="mt-5 block max-w-xl"><span class="sr-only">Search documentation</span><input class="field w-full" type="search" placeholder="Search deployment, widgets, backups…" bind:value={query} /></label>
	</header>
	<div class="mt-7 grid gap-8 lg:grid-cols-[15rem_minmax(0,1fr)]">
		<aside><nav class="sticky top-5" aria-label="Documentation"><p class="eyebrow px-2">On this page</p><ul class="mt-2 grid gap-0.5">{#each filtered as s}<li><a class="side-link" href={'#'+s.id}>{s.title}</a></li>{/each}</ul><div class="mt-5 border-t border-rule-soft pt-4"><a class="link" href="/api/v1/automation/openapi.yaml">Automation OpenAPI</a></div></nav></aside>
		<main class="min-w-0">
			{#each filtered as section}<section id={section.id} class="scroll-mt-6 border-b border-rule-soft pb-8 pt-7 first:pt-0"><p class="eyebrow">{section.summary}</p><h2 class="mt-1 text-2xl font-semibold">{section.title}</h2><div class="mt-4 space-y-3 text-[15px] leading-7">{#each section.body as p}<p>{p}</p>{/each}</div>{#if section.id === 'widgets'}<pre class="mt-4 overflow-x-auto bg-term p-4 font-mono text-[12px] text-term-ink">{'{"widgets":[{"key":"latency","kind":"line","title":"Gateway latency","group":"Operations","span":2,"ttl_seconds":120,"data":{"unit":"ms","points":[{"label":"now","value":42}]}}]}'}</pre>{/if}</section>{:else}<div class="border border-rule-soft bg-panel p-8 text-center"><h2 class="text-title font-semibold">No matching documentation</h2><p class="mt-1 text-muted">Try a shorter search term.</p></div>{/each}
		</main>
	</div>
</div>
