<script lang="ts">
	import Icon, { type IconName } from '$lib/components/ui/Icon.svelte';
	let query = $state('');
	const sections = [
		{ id:'version', title:'Version and implementation status', summary:'What this build contains and what comes next.', body:['This documentation describes BotForge 0.2.0 and the changes recorded under Unreleased in the changelog. The root VERSION file is the authoritative project version and the changelog records every notable release and in-progress change.','Version 0.2.0 added the in-house documentation, expanded widget dashboards and lifecycle, Discord bot avatars, protected Prometheus metrics, and TCP/HTTP health probes. The unreleased work adds team workspaces with administrator oversight, static site hosting with custom domains, publishing bots to GitHub, and appearance options including corner styles.','The remaining staged work is tracked in docs/implementation-status.md in the source distribution. Highest priority is removing Docker socket ownership from the panel through a narrow privileged botrunner service, followed by real egress, disk, IO, and bandwidth enforcement.'] },
		{ id:'quickstart', title:'Quick start', summary:'Create, configure and run your first bot.', body:['Choose Templates for a tested starter, or create a blank bot and upload your project in Files.','Add secrets such as DISCORD_TOKEN in Environment. Secrets are encrypted at rest and never returned after saving.','Review runtime, memory and restart policy, then start the bot. Follow build output and live logs from its page.'] },
		{ id:'deploy', title:'Deployment and GitHub', summary:'Manual uploads, repositories, automatic deploys and pushing back.', body:['Manual projects can be edited in the browser or over SFTP. GitHub projects download a repository archive without installing git on the host.','Connect GitHub under Settings, link a repository in Deploy, select the branch and optional root directory, then deploy. Automatic deploys use a signed webhook.','A failed build keeps the previous generation available. Use operation history for the exact stage and output.'] },
		{ id:'publish', title:'Publishing a bot to GitHub', summary:'Create a repository from a bot and push later changes.', body:['Deploy → Publish to GitHub creates a repository under your account or organization (private by default), pushes the bot’s files as the first commit and links the bot to it, optionally with auto-deploy. For a linked bot, Push to GitHub commits the current files to the linked branch.','Pushing uses your own GitHub connection with repository access and never force-pushes: if the branch moved on GitHub, the push stops and you deploy those changes first. With a linked folder, only that folder is replaced.','.gitignore files (root and nested) are honored. Dependencies, .git, panel metadata and .env files are always left out (.env.example is kept) and panel environment variables are never pushed. The dialog lists every file before anything is created. Limits: 5,000 files, 200 MiB, 25 MiB per file.'] },
		{ id:'workspaces', title:'Workspaces and roles', summary:'Group bots and sites for a team.', body:['Every account has a Personal workspace; create team workspaces under Settings → Workspaces and add people by the email they sign in with. The sidebar switcher scopes the overview, Sites and new bots to one workspace.','Owner and Admin act as the owner of every bot and site in the workspace. Developer creates, deploys and operates bots and sites, edits files and environment variables, but cannot change resources, delete or share. Viewer only reads status and console output.','Per-bot sharing still adds access on top. Transferring a bot moves it into the new owner’s personal workspace. Administrators see every workspace, account, bot and recent deployment under Administration.'] },
		{ id:'sites', title:'Bot Sites and public pages', summary:'A public home attached directly to each Discord bot.', body:['Open a bot’s Public page tab to create its one integrated site. Page Studio publishes a generated page with its own headline, introduction, theme, accent, custom HTML, custom CSS and an isolated live preview. Private telemetry remains under Private insights.','Switch the same address to Custom files for a complete HTML, CSS and JavaScript site. Site files is a private working draft: saving never changes production. Publish draft creates an immutable release, and older releases remain available for instant rollback.','Generated pages can expose validated declarative widgets only after a developer enables Publish bot widgets. Raw stats, command usage, events, logs, secrets, owner identity and deployment details are never part of the public page response.','Add a custom domain, create the TXT ownership record plus the shown CNAME or address record, then check DNS. The domain is served only after verification.','A site’s address is its name followed by a sites domain, such as docs.sites.example.com. Change it in the site’s Settings: the move is immediate, the old address stops working and any site may take it, while verified custom domains keep working. A name is unique on each sites domain. Administrators add further sites domains under Administration → Sites and domains; each serves only after its _botforge-domain TXT record is verified, and the reverse proxy still has to route it and hold a certificate for it.'] },
		{ id:'appearance', title:'Appearance', summary:'Theme, accent color and corners.', body:['Settings → Appearance chooses light, dark or system theme, one of twelve accent colors, and a corner style: Square (no rounding anywhere), Subtle, Default or Rounded. These preferences apply to the current browser.'] },
		{ id:'ai', title:'AI assistant', summary:'One private chat for the whole panel that knows where you are.', body:['Open it with the Ask AI button at the bottom right of any page, or the sparkle button in the header (Ctrl+.). It is one chat, not one per bot: each message carries the bot or site, section and open file you were looking at, shown as a chip above the message box that you can dismiss for a single question. Ask in plain language, for example why a bot is not starting.','It reads a bot’s status, recent console output, build and deployment logs, permitted files and variable names, and can search the web for documentation. An administrator adds an OpenAI-compatible provider (DeepSeek is the preset) in the optional AI operator step of /setup or later under Administration → Panel settings, where providers can be edited, re-keyed, enabled, disabled, deleted and tested, and models discovered. Keys are encrypted and never shown again. Hosting works without any provider.','Ask first, the default, stops on a card before a diagnostic, a file change, a restart or secure environment input. Auto repair, available while a bot or site is open, first shows its envelope (the target, the tools it covers and the run limits) and needs one approval; secure input still waits for you. There are no tools for the startup command, deployments, site publication, GitHub pushes or kill. Diagnostics run one allowed command, such as a syntax check, the tests or the bot’s entry file, in a throwaway offline copy of the files; a command that is not allowed returns the list of those that are.','Each run is limited in both modes: 12 rounds, 20 minutes, 5 diagnostics, 3 apply attempts, 2 restarts, 32 changed files, 8 MiB of changed text and 2 MiB of retained tool output. A call over a limit is refused. Every model-initiated file change, diagnostic, restart and secure input is recorded in the activity log.','Chats are private to you, kept for 90 days and listed under the history button; reloading restores the active run, pending approvals, secure-input cards, change sets and Undo. Web research may use a private self-hosted SearxNG origin, while fetched pages must be public; addresses are checked at connect time.'] },
		{ id:'widgets', title:'Dashboard and public widgets', summary:'One validated schema for private operations and opt-in public pages.', body:['Send widgets in POST /api/v1/bot-telemetry or its WebSocket. Up to 48 widgets may be changed in one push and up to 240 active widgets are returned. Keys are upserted.','Kinds: metric, status, progress, text, chart, table, link, line, area, donut, gauge, heatmap, sparkline, kv, markdown, image, log and code. Bot content stays declarative inside the operator panel.','Optional fields: group (tab name, 48 chars), span (1, 2 or 3 columns), min_height (0–800 px), position (0–1000), and ttl_seconds (30–604800). A widget older than five minutes is marked stale.','On a public Bot Site, custom CSS can target [data-widget="widget-key"] or a renderer class such as .kind-metric. Turn off Publish bot widgets to remove every widget from the public page immediately.'] },
		{ id:'widget-data', title:'Widget data shapes', summary:'Payload conventions for every renderer.', body:['metric: {value, unit?, detail?, delta?}; status: {state: good|warn|bad|neutral, text}; progress/gauge: {value, max?, label?, unit?}.','chart/line/area/sparkline: {points:[{label,value}], unit?}; donut: {values:[{label,value}]}; heatmap: {cells:[{label,value}]}.','table: {columns:[string|{label}], rows:[[string|number|{label,url}]]}; kv: {items:[{key,value}]}; text/markdown/log: {text}; code: {code, language?}; image/link: {url, alt?/label?}.'] },
		{ id:'telemetry', title:'Telemetry limits', summary:'Rates, validation and retention.', body:['The request body is at most 64 KiB. Each bot may push 60 times per minute. A named stat is stored at most once every 10 seconds.','Per push: 16 stats, 20 commands, 10 events, 48 widget updates and 48 unpublish keys. Widget data is valid non-null JSON up to 4096 bytes. Validation errors identify the offending field.','Retention is configured by the administrator from one hour to 365 days; the default is seven days. A bot also has a bounded telemetry row history.'] },
		{ id:'health', title:'Health and alerts', summary:'Heartbeats, active probes, restart behavior and notifications.', body:['A bot has three separate health signals, shown side by side under Health & alerts. Process state (in the bot header) only says whether the container runs. The heartbeat says whether the bot’s own code is alive. The probe says whether the host can reach it.','Heartbeat: every accepted telemetry push from the BotForge SDK is a heartbeat. Send the optional ready boolean as true once your client has logged in to Discord and false when it disconnects. The SDK snippet and the key it needs are under the bot’s Analytics section. A bot that never reported is unknown, never failed, and never alerts.','Probe: a TCP probe passes when a published TCP port accepts a connection; an HTTP probe sends GET to a path and passes on a 200–399 reply without following redirects. Both connect through 127.0.0.1 to a port published in Network, so they cannot reach other hosts. Check every sets the interval, Timeout marks a slow check as failed, Failures before unhealthy and Successes before healthy set how many checks in a row change the state, and Startup grace ignores failures right after a start.','Restart when unhealthy replaces a stuck container once on the transition to unhealthy, not on every failed check, so a broken deployment cannot restart in a loop. Restart policy under Startup separately retries processes that exit with bounded exponential backoff.','Discord notifications go to the channel the bot’s owner connected under Settings → Connected accounts → Discord. Choose crashes (at most one per bot per 10 minutes), deployments, backup failures and recoveries, and optionally alert once when a running bot stops reporting heartbeats for 1 minute to 1 hour. Send a test checks the connection.','Use the diagnostics page for database, container runtime, storage and runner checks.'] },
		{ id:'email', title:'Email (Mailgun)', summary:'Password reset, invitations, alert emails and security notices.', body:['Email is off until an administrator opens Administration → Panel settings → Email (Mailgun) and enters a Mailgun API key, a verified sending domain, its region (US or EU) and a sender such as BotForge <noreply@mg.example.com>. Press Send test to check the key, region and the domain\'s DNS records and to send one message. The key is stored encrypted and never shown again. The same values can be set with BOTPANEL_MAILGUN_API_KEY, BOTPANEL_MAILGUN_DOMAIN, BOTPANEL_MAILGUN_REGION and BOTPANEL_MAIL_FROM, in which case the environment wins.','With email and the panel address set, the sign-in page offers Forgot your password. The reset link works once, expires after an hour, and signs the account out everywhere when used; the request answers the same way whether or not the address has an account. Administrators can tick Email the link when inviting a user. Bot owners also get crash, deploy, backup and health alerts by email (Settings → Profile → Email turns this off), and every password or two-step change sends a security notice that cannot be turned off.','Administration → Announcements lets an administrator email HTML news or policy updates to every enabled account or to administrators only. Write the message, check the preview, send yourself a test (required before sending), then send. A notice goes to everyone in the audience; news skips accounts that turned news off in their profile. Each person sees only their own address, scripts and forms are stripped, and there is no draft, history or scheduling.','A Mailgun sandbox domain only delivers to recipients you authorize in Mailgun. BotForge does not receive Mailgun webhooks, so bounces and complaints are not tracked and nothing is retried. Email adds no background work: idle memory does not change.'] },
		{ id:'security', title:'Security and isolation', summary:'Current boundaries and production guidance.', body:['Bots run with resource limits, dropped capabilities and a read-only runtime where supported. Do not mount the Docker socket into bot containers. The panel host itself must be treated as privileged while it owns that socket.','Disable networking for bots that do not need it. Bandwidth intent is recorded but requires host traffic shaping for kernel enforcement. Put the panel behind TLS and keep encryption keys outside backups.','Use a dedicated host for untrusted tenants. Stronger isolation, egress allowlists, disk quotas, malware scanning and signed runtime verification are tracked platform hardening work.'] },
		{ id:'backups', title:'Backups and restore', summary:'Workspace, environment and restore safety.', body:['Manual and scheduled backups are checksummed. Environment inclusion is explicit because it contains encrypted secrets.','A restore creates a safety backup first and records verification details. Keep off-host copies; a backup on the same disk is not disaster recovery.'] },
		{ id:'automation', title:'Automation API', summary:'Tokens, idempotency and config-as-code foundations.', body:['Create scoped automation tokens under SFTP and API keys. Send an Idempotency-Key on mutating requests so CI retries do not duplicate work.','The machine-readable specification is available at /api/v1/automation/openapi.yaml. Tokens are shown once and should be kept in a secret store.'] },
		{ id:'admin-tools', title:'Host, logs and environment', summary:'Administrators: resources, per-bot usage, panel logs and editing variables.', body:['Administration → Host shows the machine and BotForge itself. Resources has live CPU, memory, load, disk and network figures with history charts from 1 hour to 30 days, the Docker runner, storage use and a list of things that need attention. Bots shows what each running bot uses against its limits. Panel logs follows the panel’s own log with level filter, search, copy and download; secrets are redacted and the view starts empty after a restart (the full log is in journalctl or docker logs).','Administration → Environment lists every BOTPANEL_ variable with its default and where its value comes from, and edits most of them from the browser. Values are checked as a whole before they are stored and apply after a restart; the page shows what is waiting and offers Restart panel when systemd or a container restart policy will start BotForge again. Variables read before the database opens, and those that widen what the panel may do to the host, stay in the environment file. From the host, botpanel env lists the saved values and botpanel env reset drops them.','Press Ctrl+K anywhere to search pages, settings, environment variables, bots, sites, people, AI chats and actions; several words narrow the search and Tab switches scope.'] },
		{ id:'operations', title:'Operations guide', summary:'Install, update, diagnose and recover.', body:['Deploy with the provided container or systemd units, configure the public URL, and verify /api/v1/healthz and /api/v1/readyz.','Before upgrades, take and verify a backup. Review release notes, apply the new binary or image, and confirm the schema migration and readiness checks.','For recovery, preserve the database, workspace directory and encryption keys together. Without matching key material, sealed secrets cannot be recovered.'] }
	];
	const filtered = $derived(sections.filter((s)=>(s.title+' '+s.summary+' '+s.body.join(' ')).toLowerCase().includes(query.trim().toLowerCase())));
	const iconFor = (id: string): IconName => ({ version:'commit', quickstart:'rocket', deploy:'github', publish:'upload', workspaces:'users', sites:'globe', ai:'bolt', appearance:'sun', widgets:'grid', 'widget-data':'code', telemetry:'activity', health:'shield', security:'key', backups:'archive', automation:'bolt', operations:'terminal' } as Record<string, IconName>)[id] ?? 'book';
</script>

<svelte:head><title>Documentation · BotForge</title><meta name="description" content="BotForge installation, deployment, dashboard widget, telemetry, security and operations documentation." /></svelte:head>

<div class="mx-auto max-w-7xl px-4 py-5 sm:px-6 lg:px-8 lg:py-8">
	<header class="relative overflow-hidden rounded-card bg-term px-6 py-10 text-term-ink sm:px-10 sm:py-14 lg:px-14">
		<div class="pointer-events-none absolute -top-24 right-[-8rem] size-[28rem] rounded-pill bg-action/25 blur-3xl"></div>
		<div class="relative grid items-end gap-10 lg:grid-cols-[minmax(0,1.25fr)_minmax(19rem,.75fr)]">
			<div>
				<a href="/" class="inline-flex items-center gap-2 text-small text-white/55"><Icon name="book" size={14} />BotForge field guide</a>
				<h1 class="mt-7 max-w-[12ch] text-4xl font-semibold leading-[.98] tracking-[-.045em] sm:text-6xl">Build the bot. Operate it. Give it a public home.</h1>
				<p class="mt-5 max-w-2xl text-base leading-7 text-white/60">Practical paths through deployment, Page Studio, public widgets, domains, team access and recovery—with the security boundary shown wherever it matters.</p>
			</div>
			<div class="rounded-tile border border-white/12 bg-white/6 p-4 backdrop-blur">
				<p class="text-small text-white/50">Find a guide</p>
				<label class="relative mt-2 block"><span class="sr-only">Search documentation</span><Icon name="search" size={15} class="pointer-events-none absolute top-1/2 left-3 -translate-y-1/2 text-white/45" /><input class="field border-white/15 bg-black/20 pl-9 text-white placeholder:text-white/35" type="search" placeholder="Sites, widgets, restore…" bind:value={query} /></label>
				<div class="mt-4 grid grid-cols-3 gap-px overflow-hidden rounded-control bg-white/10 text-center"><div class="bg-term/80 p-2"><strong class="block text-lg">6</strong><span class="text-[11px] text-white/45">runtimes</span></div><div class="bg-term/80 p-2"><strong class="block text-lg">18</strong><span class="text-[11px] text-white/45">widgets</span></div><div class="bg-term/80 p-2"><strong class="block text-lg">2</strong><span class="text-[11px] text-white/45">site modes</span></div></div>
			</div>
		</div>
	</header>

	<div class="mt-7 grid gap-8 lg:grid-cols-[16rem_minmax(0,1fr)]">
		<aside>
			<nav class="sticky top-5" aria-label="Documentation">
				<p class="px-2 text-small font-semibold">Contents</p>
				<ul class="mt-2 max-h-[calc(100dvh-9rem)] space-y-0.5 overflow-auto pr-1">{#each filtered as s}<li><a class="side-link flex items-center gap-2" href={'#'+s.id}><Icon name={iconFor(s.id)} size={13} class="text-muted" /><span class="truncate">{s.title}</span></a></li>{/each}</ul>
				<div class="mt-5 border-t border-rule-soft px-2 pt-4"><a class="link inline-flex items-center gap-1.5" href="/api/v1/automation/openapi.yaml"><Icon name="code" size={13} />Automation OpenAPI</a></div>
			</nav>
		</aside>

		<main class="min-w-0 space-y-5">
			{#each filtered as section}
				<section id={section.id} class="scroll-mt-5 overflow-hidden rounded-card border border-rule-soft bg-panel">
					<header class="grid gap-3 border-b border-rule-soft bg-paper/40 px-5 py-5 sm:grid-cols-[3rem_minmax(0,1fr)] sm:px-7">
						<span class="grid size-11 place-items-center rounded-tile border border-rule-soft bg-raised text-action"><Icon name={iconFor(section.id)} size={18} /></span>
						<div><h2 class="text-2xl font-semibold tracking-tight">{section.title}</h2><p class="mt-0.5 text-muted">{section.summary}</p></div>
					</header>

					<div class="px-5 py-6 sm:px-7 sm:py-7">
						{#if section.id === 'quickstart'}
							<ol class="grid gap-px overflow-hidden rounded-tile border border-rule-soft bg-rule-soft sm:grid-cols-3">
								{#each section.body as p, i}<li class="bg-raised p-4"><span class="grid size-7 place-items-center rounded-pill bg-action text-small font-semibold text-action-ink">{i + 1}</span><p class="mt-3 leading-6">{p}</p></li>{/each}
							</ol>
						{:else}
							<div class="max-w-[78ch] space-y-3 text-[15px] leading-7">{#each section.body as p}<p>{p}</p>{/each}</div>
						{/if}

						{#if section.id === 'sites'}
							<div class="mt-6 overflow-hidden rounded-tile border border-rule-soft">
								<div class="grid items-stretch bg-rule-soft sm:grid-cols-[1fr_auto_1fr_auto_1fr]">
									<div class="bg-raised p-4"><Icon name="discord" size={18} class="text-action" /><strong class="mt-3 block">Bot</strong><span class="text-small text-muted">Publishes validated widgets</span></div><div class="hidden items-center bg-raised px-1 text-muted sm:flex">›</div>
									<div class="bg-raised p-4"><Icon name="pencil" size={18} class="text-action" /><strong class="mt-3 block">Page Studio</strong><span class="text-small text-muted">Composes the public surface</span></div><div class="hidden items-center bg-raised px-1 text-muted sm:flex">›</div>
									<div class="bg-raised p-4"><Icon name="globe" size={18} class="text-action" /><strong class="mt-3 block">Sites origin</strong><span class="text-small text-muted">Runs author HTML away from panel cookies</span></div>
								</div>
								<div class="border-t border-rule-soft bg-run/8 px-4 py-3 text-small text-run"><strong>Public:</strong> page copy, author HTML/CSS and opted-in widgets. <strong class="ml-2">Private:</strong> secrets, console, events, command analytics, people and deployments.</div>
							</div>
						{:else if section.id === 'widgets'}
							<div class="mt-6 grid gap-3 sm:grid-cols-3">
								<div class="rounded-tile border border-rule-soft bg-raised p-4"><p class="text-small text-muted">Gateway latency</p><p class="mt-2 text-3xl font-semibold">42 <small class="text-small text-muted">ms</small></p><div class="mt-3 flex h-8 items-end gap-1">{#each [35,52,41,68,55,76,62,84] as h}<i class="flex-1 bg-action/65" style={`height:${h}%`}></i>{/each}</div></div>
								<div class="rounded-tile border border-rule-soft bg-raised p-4"><p class="text-small text-muted">Discord gateway</p><p class="mt-3 flex items-center gap-2 font-semibold"><span class="size-2 rounded-pill bg-run"></span>Connected</p><p class="mt-5 text-small text-muted">Updated 8 seconds ago</p></div>
								<div class="rounded-tile border border-rule-soft bg-raised p-4"><p class="text-small text-muted">Queue</p><p class="mt-2 text-3xl font-semibold">68%</p><div class="mt-3 h-2 overflow-hidden rounded-pill bg-paper-2"><div class="h-full w-[68%] bg-action"></div></div></div>
							</div>
							<div class="mt-4 grid gap-3 lg:grid-cols-2"><div><p class="mb-1 text-small font-medium">Telemetry payload</p><pre class="max-h-72 overflow-auto rounded-tile bg-term p-4 font-mono text-[12px] leading-5 text-term-ink">{'{"widgets":[{"key":"latency","kind":"line","title":"Gateway latency","group":"Operations","span":2,"ttl_seconds":120,"data":{"unit":"ms","points":[{"label":"now","value":42}]}}]}'}</pre></div><div><p class="mb-1 text-small font-medium">Public-page CSS hook</p><pre class="max-h-72 overflow-auto rounded-tile bg-term p-4 font-mono text-[12px] leading-5 text-term-ink">{'[data-widget="latency"] {\n  grid-column: span 2;\n  border-color: var(--accent);\n}\n\n.kind-metric .metric {\n  font-variant-numeric: tabular-nums;\n}'}</pre></div></div>
						{:else if section.id === 'security'}
							<div class="mt-5 grid gap-3 sm:grid-cols-2"><div class="rounded-tile border border-run/30 bg-run/8 p-4"><strong class="flex items-center gap-2 text-run"><Icon name="shield" size={15} />Enforced now</strong><p class="mt-2 text-small leading-6">App authorization, separate Sites origin, non-root containers, read-only runtime, capability drops and resource limits.</p></div><div class="rounded-tile border border-warn/30 bg-warn/8 p-4"><strong class="flex items-center gap-2 text-warn"><Icon name="alert" size={15} />Host controls still required</strong><p class="mt-2 text-small leading-6">Egress policy, disk quotas, IO and bandwidth need kernel, filesystem or network enforcement outside stored configuration.</p></div></div>
						{/if}
					</div>
				</section>
			{:else}
				<div class="rounded-card border border-rule-soft bg-panel p-10 text-center"><Icon name="search" size={24} class="mx-auto text-muted" /><h2 class="mt-3 text-title font-semibold">No matching documentation</h2><p class="mt-1 text-muted">Try a shorter search term or a feature name.</p></div>
			{/each}
		</main>
	</div>
</div>
