<script lang="ts">
	import { onMount } from 'svelte';
	import { api, ApiError } from '$lib/api/client';
	import { toast } from '$lib/ui/toast.svelte';
	type P = { id: string; name: string; enabled: boolean; default: boolean; base_url: string; chat_path: string; models_path: string; default_model: string; max_output_tokens: number; temperature: number; timeout_ms: number; key_set: boolean };
	type S = { search_enabled: boolean; fetch_enabled: boolean; base_url: string; key_count: number; results: number; language: string; categories: string; time_range: string; safe_search: number };
	let providers=$state<P[]>([]), search=$state<S|null>(null), error=$state(''), key=$state(''), searchKeys=$state('');
	let form=$state({name:'DeepSeek',enabled:true,default:true,base_url:'https://api.deepseek.com',chat_path:'/chat/completions',models_path:'/models',default_model:'deepseek-chat',max_output_tokens:4096,temperature:.2,timeout_ms:120000});
	const msg=(e:unknown)=>e instanceof ApiError?e.message:'The AI settings request failed.';
	async function load(){try{providers=(await api<{providers:P[]}>('GET','/admin/ai/providers')).providers;search=await api<S>('GET','/admin/ai/search')}catch(e){error=msg(e)}}
	async function add(e:SubmitEvent){e.preventDefault();try{await api('POST','/admin/ai/providers',{...form,key,input_price_micros:null,output_price_micros:null,context_size:null});key='';await load();toast('AI provider saved','success')}catch(x){error=msg(x)}}
	async function test(id:string){try{const r=await api<Record<string,boolean>>('POST',`/admin/ai/providers/${id}/test`);toast(r.tool_call?'Provider supports streaming tools':'Provider responded, but tool calling was not verified',r.tool_call?'success':'fail')}catch(e){error=msg(e)}}
	async function saveSearch(e:SubmitEvent){e.preventDefault();if(!search)return;try{const keys=searchKeys.trim()?searchKeys.split('\n').map(x=>x.trim()).filter(Boolean):undefined;search=await api<S>('PUT','/admin/ai/search',{...search,keys,language:search.language,categories:search.categories,time_range:search.time_range});searchKeys='';toast('Research settings saved','success')}catch(x){error=msg(x)}}
	onMount(load);
</script>
<section class="card p-5 sm:p-6">
	<h3 class="text-title font-semibold">AI operator providers</h3><p class="mt-1 text-small text-muted">OpenAI-compatible endpoints only. Keys are encrypted and browsers receive only a key-set marker.</p>
	{#if error}<p class="mt-3 text-small text-fail">{error}</p>{/if}
	<div class="mt-4 space-y-2">{#each providers as p}<div class="flex flex-wrap items-center gap-2 rounded-control border border-rule-soft p-3"><strong>{p.name}</strong><span class="pill" data-tone={p.enabled?'run':undefined}>{p.enabled?'Enabled':'Disabled'}</span>{#if p.default}<span class="pill">Default</span>{/if}<span class="flex-1 text-small text-muted">{p.default_model} · key {p.key_set?'set':'missing'}</span><button type="button" class="btn btn-sm" onclick={()=>test(p.id)}>Test capabilities</button></div>{/each}</div>
	<form class="mt-4 grid gap-3 border-t border-rule-soft pt-4 sm:grid-cols-2" onsubmit={add}><label><span class="label">Name</span><input class="field" bind:value={form.name}/></label><label><span class="label">Base API URL</span><input class="field font-mono" bind:value={form.base_url}/></label><label><span class="label">Default model ID</span><input class="field font-mono" bind:value={form.default_model}/></label><label><span class="label">Encrypted bearer key</span><input class="field" type="password" bind:value={key} autocomplete="new-password" required/></label><label class="flex items-center gap-2"><input type="checkbox" bind:checked={form.default}/>Make default</label><div class="text-right"><button class="btn btn-primary">Add provider</button></div></form>
</section>
{#if search}<section class="card p-5 sm:p-6"><h3 class="text-title font-semibold">Web research</h3><p class="mt-1 text-small text-muted">SearxNG/Risa-compatible search. Search credentials are sent only to this origin; fetched result pages receive none.</p><form class="mt-4 grid gap-3 sm:grid-cols-2" onsubmit={saveSearch}><label class="flex items-center gap-2"><input type="checkbox" bind:checked={search.search_enabled}/>Enable search</label><label class="flex items-center gap-2"><input type="checkbox" bind:checked={search.fetch_enabled}/>Enable public page fetching</label><label class="sm:col-span-2"><span class="label">Search base URL</span><input class="field font-mono" bind:value={search.base_url}/></label><label><span class="label">Results per query</span><input class="field" type="number" min="1" max="10" bind:value={search.results}/></label><label><span class="label">Safe search</span><select class="field" bind:value={search.safe_search}><option value={0}>Off</option><option value={1}>Moderate</option><option value={2}>Strict</option></select></label><label class="sm:col-span-2"><span class="label">Replace API keys (one per line)</span><textarea class="field min-h-20 font-mono" bind:value={searchKeys} placeholder={search.key_count?`${search.key_count} encrypted key(s) already set`:'Optional'}></textarea></label><div class="sm:col-span-2 text-right"><button class="btn btn-primary">Save research settings</button></div></form></section>{/if}
